/**
 * exportDatasets.js
 * Comprehensive configuration for CampusNode Export Center datasets,
 * filter schemas, column dictionaries, and formatters.
 */

export const ACADEMIC_SESSIONS = [
  { id: "all", label: "All Sessions" },
  { id: "2026–27", label: "2026–27" },
  { id: "2025–26", label: "2025–26" },
  { id: "2024–25", label: "2024–25" },
  { id: "2023–24", label: "2023–24" },
];

export const SEMESTERS = [
  { id: "all", label: "All Semesters" },
  { id: "Odd", label: "Odd Semester (July–Dec)" },
  { id: "Even", label: "Even Semester (Jan–June)" },
];

export const EXPORT_DATASETS = {
  events: {
    id: "events",
    label: "Events",
    category: "Academic & Campus Activities",
    description: "Export event listings, schedules, venue details, approval states, and seat metrics.",
    icon: "ri-calendar-event-line",
    defaultColumns: ["title", "clubName", "venue", "startTime", "entryFee", "reviewStatus", "registeredCount"],
    allColumns: [
      { id: "id", label: "Event ID" },
      { id: "title", label: "Event Title" },
      { id: "clubName", label: "Organising Club" },
      { id: "venue", label: "Venue" },
      { id: "startTime", label: "Start Date & Time" },
      { id: "endTime", label: "End Date & Time" },
      { id: "reviewStatus", label: "Approval Status" },
      { id: "entryFee", label: "Entry Fee (₹)" },
      { id: "eventType", label: "Type (Paid/Free)" },
      { id: "registeredCount", label: "Registrations" },
      { id: "registrationType", label: "Registration Mode" },
      { id: "payoutStatus", label: "Payout Status" },
      { id: "registrationDeadline", label: "Deadline" },
      { id: "createdAt", label: "Created Date" },
    ],
    filterFields: [
      {
        id: "reviewStatus",
        label: "Approval Status",
        type: "select",
        options: [
          { value: "all", label: "All Statuses" },
          { value: "PUBLISHED", label: "Published" },
          { value: "PENDING", label: "Pending Review" },
          { value: "REJECTED", label: "Rejected" },
          { value: "DRAFT", label: "Draft" },
        ],
      },
      {
        id: "eventType",
        label: "Event Fee Type",
        type: "select",
        options: [
          { value: "all", label: "All Types" },
          { value: "Free", label: "Free Events" },
          { value: "Paid", label: "Paid Events" },
        ],
      },
      {
        id: "registrationType",
        label: "Registration Mode",
        type: "select",
        options: [
          { value: "all", label: "All Modes" },
          { value: "individual", label: "Individual" },
          { value: "team", label: "Team" },
        ],
      },
    ],
  },

  registrations: {
    id: "registrations",
    label: "Registrations",
    category: "Participation & Enrollment",
    description: "Export student registration records, roll numbers, fee payments, and UTR references.",
    icon: "ri-group-line",
    defaultColumns: ["studentName", "rollNo", "eventName", "clubName", "status", "paymentStatus", "amountPaid", "createdAt"],
    allColumns: [
      { id: "id", label: "Registration ID" },
      { id: "studentName", label: "Student Name" },
      { id: "rollNo", label: "Roll Number" },
      { id: "email", label: "Email Address" },
      { id: "eventName", label: "Event Title" },
      { id: "clubName", label: "Club Name" },
      { id: "status", label: "Registration Status" },
      { id: "paymentStatus", label: "Payment Status" },
      { id: "amountPaid", label: "Amount Paid (₹)" },
      { id: "transactionId", label: "UTR / Transaction ID" },
      { id: "createdAt", label: "Registration Date" },
    ],
    filterFields: [
      {
        id: "status",
        label: "Participation Status",
        type: "select",
        options: [
          { value: "all", label: "All Statuses" },
          { value: "REGISTERED", label: "Registered" },
          { value: "ATTENDED", label: "Attended" },
          { value: "WAITLISTED", label: "Waitlisted" },
          { value: "CANCELLED", label: "Cancelled" },
        ],
      },
      {
        id: "paymentStatus",
        label: "Payment Status",
        type: "select",
        options: [
          { value: "all", label: "All Payment Statuses" },
          { value: "SUCCESS", label: "Success" },
          { value: "APPROVED", label: "Approved" },
          { value: "PENDING", label: "Pending" },
          { value: "REJECTED", label: "Rejected" },
        ],
      },
    ],
  },

  students: {
    id: "students",
    label: "Students",
    category: "System Administration",
    description: "Export student user directory, roll numbers, branches, and account verification statuses.",
    icon: "ri-user-line",
    defaultColumns: ["name", "rollNo", "email", "branch", "year", "program", "userCategory", "createdAt"],
    allColumns: [
      { id: "id", label: "Student ID" },
      { id: "name", label: "Student Name" },
      { id: "rollNo", label: "Roll Number" },
      { id: "email", label: "Email Address" },
      { id: "branch", label: "Branch" },
      { id: "year", label: "Year" },
      { id: "program", label: "Program" },
      { id: "userCategory", label: "User Role Category" },
      { id: "isVerified", label: "Email Verified" },
      { id: "isBlocked", label: "Status (Blocked)" },
      { id: "createdAt", label: "Registered Date" },
    ],
    filterFields: [
      {
        id: "userCategory",
        label: "User Category Filter",
        type: "select",
        options: [
          { value: "students_only", label: "Regular Students Only" },
          { value: "club_heads_only", label: "Club Heads / Execs Only" },
          { value: "all", label: "All Enrolled Accounts" },
        ],
      },
      {
        id: "branch",
        label: "Branch / Dept",
        type: "select",
        options: [
          { value: "all", label: "All Branches" },
          { value: "CSE", label: "CSE" },
          { value: "ECE", label: "ECE" },
          { value: "EE", label: "EE" },
          { value: "ME", label: "ME" },
          { value: "CE", label: "CE" },
          { value: "ICE", label: "ICE" },
          { value: "CHE", label: "CHE" },
          { value: "TT", label: "TT" },
          { value: "IPE", label: "IPE" },
          { value: "BT", label: "BT" },
        ],
      },
      {
        id: "year",
        label: "Academic Year",
        type: "select",
        options: [
          { value: "all", label: "All Years" },
          { value: "1st Year", label: "1st Year" },
          { value: "2nd Year", label: "2nd Year" },
          { value: "3rd Year", label: "3rd Year" },
          { value: "4th Year", label: "4th Year" },
        ],
      },
      {
        id: "program",
        label: "Degree Program",
        type: "select",
        options: [
          { value: "all", label: "All Programs" },
          { value: "BTECH", label: "B.Tech" },
          { value: "MTECH", label: "M.Tech" },
          { value: "OTHER", label: "Other" },
        ],
      },
    ],
  },

  clubs: {
    id: "clubs",
    label: "Clubs",
    category: "System Administration",
    description: "Export registered student organizations, faculty advisors, and bank account summaries.",
    icon: "ri-community-line",
    defaultColumns: ["clubName", "category", "facultyName", "facultyEmail", "officialClubEmail", "createdAt"],
    allColumns: [
      { id: "id", label: "Club ID" },
      { id: "clubName", label: "Club Name" },
      { id: "category", label: "Category" },
      { id: "facultyName", label: "Faculty Coordinator" },
      { id: "facultyEmail", label: "Faculty Email" },
      { id: "officialClubEmail", label: "Official Club Email" },
      { id: "bankName", label: "Bank Name" },
      { id: "accountHolderName", label: "Account Holder" },
      { id: "accountNumberMasked", label: "Account Number (Masked)" },
      { id: "ifscCode", label: "IFSC Code" },
      { id: "upiId", label: "UPI ID" },
      { id: "createdAt", label: "Created Date" },
    ],
    filterFields: [
      {
        id: "category",
        label: "Club Category",
        type: "select",
        options: [
          { value: "all", label: "All Categories" },
          { value: "Technical", label: "Technical" },
          { value: "Cultural", label: "Cultural" },
          { value: "Sports", label: "Sports" },
          { value: "Social", label: "Social" },
        ],
      },
    ],
  },

  transactions: {
    id: "transactions",
    label: "Financial Transactions",
    category: "Finance & Accounting",
    description: "Export detailed paid event transaction verification records, UTR strings, and auditor reviews.",
    icon: "ri-wallet-3-line",
    defaultColumns: ["transactionId", "studentName", "eventName", "clubName", "amountPaid", "paymentStatus", "createdAt"],
    allColumns: [
      { id: "transactionId", label: "UTR / Transaction ID" },
      { id: "studentName", label: "Student Name" },
      { id: "rollNo", label: "Roll Number" },
      { id: "email", label: "Student Email" },
      { id: "eventName", label: "Event Title" },
      { id: "clubName", label: "Club Name" },
      { id: "payerName", label: "Payer Name" },
      { id: "amountPaid", label: "Amount Paid (₹)" },
      { id: "paymentStatus", label: "Payment Status" },
      { id: "paymentRemarks", label: "Remarks" },
      { id: "paymentReviewedBy", label: "Reviewed By" },
      { id: "createdAt", label: "Transaction Date" },
    ],
    filterFields: [
      {
        id: "paymentStatus",
        label: "Verification Status",
        type: "select",
        options: [
          { value: "all", label: "All Statuses" },
          { value: "PENDING", label: "Pending Review" },
          { value: "APPROVED", label: "Approved" },
          { value: "REJECTED", label: "Rejected" },
          { value: "NEED_MORE_DETAILS", label: "Need More Details" },
        ],
      },
    ],
  },

  payouts: {
    id: "payouts",
    label: "Payouts",
    category: "Finance & Accounting",
    description: "Export settlement totals, fee collection revenues, and payout completion statuses.",
    icon: "ri-bank-card-line",
    defaultColumns: ["title", "clubName", "entryFee", "registeredCount", "totalRevenue", "payoutStatus"],
    allColumns: [
      { id: "id", label: "Event ID" },
      { id: "title", label: "Event Title" },
      { id: "clubName", label: "Club Name" },
      { id: "entryFee", label: "Entry Fee (₹)" },
      { id: "registeredCount", label: "Registrations" },
      { id: "totalRevenue", label: "Total Revenue (₹)" },
      { id: "payoutStatus", label: "Payout Status" },
      { id: "startTime", label: "Event Start Date" },
      { id: "registrationDeadline", label: "Deadline" },
    ],
    filterFields: [
      {
        id: "payoutStatus",
        label: "Settlement Status",
        type: "select",
        options: [
          { value: "all", label: "All Statuses" },
          { value: "PENDING", label: "Pending" },
          { value: "COMPLETED", label: "Completed" },
        ],
      },
    ],
  },
};
