services:
  postgres:
    image: postgres:16
    container_name: clubsetu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: clubsetu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: himanshu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
